In [1]:
import pandas as pd

In [39]:
mydata = pd.DataFrame(
    {'year': range(1900, 2017)}
)
china = mydata.copy()
usa = mydata.copy()
uk = mydata.copy()
canada = mydata.copy()
china['country'] = 'China'
china['gdp'] = mydata['year'] * 2 + 1000
usa['country'] = 'USA'
usa['gdp'] = mydata['year'] * 3 + 1000
uk['country'] = 'UK'
uk['gdp'] = mydata['year'] + 100
canada['country'] = 'Canada'
canada['gdp'] = mydata['year'] * 1.5 + 200
alldata = pd.concat([china, usa])
alldata.reset_index(drop=True, inplace=True)

In [40]:
import numpy as np

In [41]:
data = pd.get_dummies(alldata)
data['country'] = alldata['country']

In [42]:
from sklearn.model_selection import GroupKFold, KFold

In [43]:
from ravenclaw.regression import Validator, Regressor

In [44]:
data.tail()

     year   gdp  country_China  country_USA country
229  2012  7036              0            1     USA
230  2013  7039              0            1     USA
231  2014  7042              0            1     USA
232  2015  7045              0            1     USA
233  2016  7048              0            1     USA

In [45]:
from ravenclaw.preprocessing import PolynomialTransformer

In [46]:
validator = Validator(folds=KFold(n_splits=10), regressor=Regressor(name='simple', polynomial_model=PolynomialTransformer(degree=2)))

In [47]:
X_training = data.drop(axis=1, labels=['gdp', 'country'])
y_training = data['gdp']

In [48]:
validator.validate(X=X_training, y=y_training, groups=data['country'])

regressor: simple
 0.2 seconds elapsed   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ 100.00%  | MAPE:1.21e-14, RMSE:7.02e-13, nRMSE:1.26e-16

In [49]:
reg = validator._trained_regressors[0]

In [50]:
reg.coefficients

,coefficient,normalized,normalizer_mean,normalizer_std,value,actual_value
0,intercept,False,0.000000e+00,1.000000,6.017514e+03,6.017514e+03
1,year country_USA,True,1.090886e+03,975.236939,7.669107e+02,7.863839e-01
2,country_USA,True,5.571429e-01,0.497911,2.773587e+02,5.570450e+02
3,year country_China,True,8.724286e+02,981.047881,-2.095676e+02,-2.136161e-01
4,country_China,True,4.428571e-01,0.497911,1.385473e+02,2.782572e+02
5,year,True,1.963314e+03,31.542578,6.982316e+01,2.213616e+00
6,country_China^2,True,4.428571e-01,0.497911,6.940574e+01,1.393939e+02
7,country_USA^2,True,5.571429e-01,0.497911,-6.940574e+01,-1.393939e+02
8,year^2,True,3.855593e+06,123742.434115,-1.948308e-11,-1.574487e-16

In [51]:
alldata['c1'] = alldata['year'] * alldata['country_USA'] * 7.863839e-01

KeyError: 'country_USA'

In [38]:
alldata['by_coef'] = 4.179295e3 + 1.197547e0 * alldata['year'] * alldata['country_USA']# -8.024525e-1 * alldata['year'] * alldata['country_UK'] -1.198970e+03*alldata['country_UK'] -3.024525e-01*alldata['year']*alldata['country_Canada']

KeyError: 'country_USA'

In [19]:
validator._validation_results

,year,country_Canada,country_China,country_UK,country_USA,gdp,regressor,test_set,prediction,error
0,1900,0,1,0,0,4800.0,simple,0,4800,2.72848e-12
1,1901,0,1,0,0,4802.0,simple,0,4802,2.72848e-12
2,1902,0,1,0,0,4804.0,simple,0,4804,2.72848e-12
3,1903,0,1,0,0,4806.0,simple,0,4806,2.72848e-12
4,1904,0,1,0,0,4808.0,simple,0,4808,2.72848e-12
5,1905,0,1,0,0,4810.0,simple,0,4810,1.81899e-12
6,1906,0,1,0,0,4812.0,simple,0,4812,1.81899e-12
7,1907,0,1,0,0,4814.0,simple,0,4814,1.81899e-12
8,1908,0,1,0,0,4816.0,simple,0,4816,1.81899e-12
9,1909,0,1,0,0,4818.0,simple,0,4818,1.81899e-12
10,1910,0,1,0,0,4820.0,simple,0,4820,1.81899e-12
11,1911,0,1,0,0,4822.0,simple,0,4822,1.81899e-12
12,1912,0,1,0,0,4824.0,simple,0,4824,9.09495e-13
13,1913,0,1,0,0,4826.0,simple,0,4826,1.81899e-12
14,1914,0,1,0,0,4828.0,simple,0,4828,9.09495e-13
15,1915,0,1,0,0,4830.0,simple,0,4830,9.09495e-13
16,1916,0,1,0,0,4832.0,simple,0,4832,9.09495e-13
17,1917,0,1,0,0,4834.0,simple,0,4834,9.09495e-13
18,1918,0,1,0,0,4836.0,simple,0,4836,9.09495e-13
19,1919,0,1,0,0,4838.0,simple,0,4838,9.09495e-13
20,1920,0,1,0,0,4840.0,simple,0,4840,9.09495e-13
21,1921,0,1,0,0,4842.0,simple,0,4842,9.09495e-13
22,1922,0,1,0,0,4844.0,simple,0,4844,0
23,1923,0,1,0,0,4846.0,simple,0,4846,0
24,1924,0,1,0,0,4848.0,simple,0,4848,0
25,1925,0,1,0,0,4850.0,simple,0,4850,0
26,1926,0,1,0,0,4852.0,simple,0,4852,0
27,1927,0,1,0,0,4854.0,simple,0,4854,0
28,1928,0,1,0,0,4856.0,simple,0,4856,0
29,1929,0,1,0,0,4858.0,simple,0,4858,0
...,...,...,...,...,...,...,...,...,...,...
438,1987,1,0,0,0,3180.5,simple,9,3180.5,-1.36424e-12
439,1988,1,0,0,0,3182.0,simple,9,3182,-1.81899e-12
440,1989,1,0,0,0,3183.5,simple,9,3183.5,-1.81899e-12
441,1990,1,0,0,0,3185.0,simple,9,3185,-1.81899e-12
442,1991,1,0,0,0,3186.5,simple,9,3186.5,-1.36424e-12
443,1992,1,0,0,0,3188.0,simple,9,3188,-1.81899e-12
444,1993,1,0,0,0,3189.5,simple,9,3189.5,-1.81899e-12
445,1994,1,0,0,0,3191.0,simple,9,3191,-1.36424e-12
446,1995,1,0,0,0,3192.5,simple,9,3192.5,-1.81899e-12
447,1996,1,0,0,0,3194.0,simple,9,3194,-1.36424e-12
448,1997,1,0,0,0,3195.5,simple,9,3195.5,-1.81899e-12
449,1998,1,0,0,0,3197.0,simple,9,3197,-1.36424e-12
450,1999,1,0,0,0,3198.5,simple,9,3198.5,-1.36424e-12
451,2000,1,0,0,0,3200.0,simple,9,3200,-1.36424e-12
452,2001,1,0,0,0,3201.5,simple,9,3201.5,-1.36424e-12
453,2002,1,0,0,0,3203.0,simple,9,3203,-1.36424e-12
454,2003,1,0,0,0,3204.5,simple,9,3204.5,-1.36424e-12
455,2004,1,0,0,0,3206.0,simple,9,3206,-1.36424e-12
456,2005,1,0,0,0,3207.5,simple,9,3207.5,-9.09495e-13
457,2006,1,0,0,0,3209.0,simple,9,3209,-1.36424e-12
458,2007,1,0,0,0,3210.5,simple,9,3210.5,-1.36424e-12
459,2008,1,0,0,0,3212.0,simple,9,3212,-1.36424e-12
460,2009,1,0,0,0,3213.5,simple,9,3213.5,-9.09495e-13
461,2010,1,0,0,0,3215.0,simple,9,3215,-9.09495e-13
462,2011,1,0,0,0,3216.5,simple,9,3216.5,-9.09495e-13
463,2012,1,0,0,0,3218.0,simple,9,3218,-1.36424e-12
464,2013,1,0,0,0,3219.5,simple,9,3219.5,-9.09495e-13
465,2014,1,0,0,0,3221.0,simple,9,3221,-9.09495e-13
466,2015,1,0,0,0,3222.5,simple,9,3222.5,-9.09495e-13
467,2016,1,0,0,0,3224.0,simple,9,3224,-9.09495e-13

In [13]:
reg.test(data=data, y_true=data['gdp'])

array([4812.77928888, 4814.62303888, 4816.46678888, 4818.31053888,
       4820.15428888, 4822.00585138, 4823.84960138, 4825.69335138,
       4827.53710138, 4829.38085138, 4831.22460138, 4833.06835138,
       4834.91210138, 4836.75585138, 4838.60741388, 4840.45116388,
       4842.29491388, 4844.13866388, 4845.98241388, 4847.82616388,
       4849.66991388, 4851.51366388, 4853.35741388, 4855.20897638,
       4857.05272638, 4858.89647638, 4860.74022638, 4862.58397638,
       4864.42772638, 4866.27147638, 4868.11522638, 4869.95897638,
       4871.81053888, 4873.65428888, 4875.49803888, 4877.34178888,
       4879.18553888, 4881.02928888, 4882.87303888, 4884.71678888,
       4886.56053888, 4888.41210138, 4890.25585138, 4892.09960138,
       4893.94335138, 4895.78710138, 4897.63085138, 4899.47460138,
       4901.31835138, 4903.16210138, 4905.01366388, 4906.85741388,
       4908.70116388, 4910.54491388, 4912.38866388, 4914.23241388,
       4916.07616388, 4917.91991388, 4919.76366388, 4921.61522638,
       4923.45897638, 4925.30272638, 4927.14647638, 4928.99022638,
       4930.83397638, 4932.67772638, 4934.52147638, 4936.36522638,
       4938.21678888, 4940.06053888, 4941.90428888, 4943.74803888,
       4945.59178888, 4947.43553888, 4949.27928888, 4951.12303888,
       4952.96678888, 4954.81835138, 4956.66210138, 4958.50585138,
       4960.34960138, 4962.19335138, 4964.03710138, 4965.88085138,
       4967.72460138, 4969.56835138, 4971.41991388, 4973.26366388,
       4975.10741388, 4976.95116388, 4978.79491388, 4980.63866388,
       4982.48241388, 4984.32616388, 4986.16991388, 4988.02147638,
       4989.86522638, 4991.70897638, 4993.55272638, 4995.39647638,
       4997.24022638, 4999.08397638, 5000.92772638, 5002.77147638,
       5004.62303888, 5006.46678888, 5008.31053888, 5010.15428888,
       5011.99803888, 5013.84178888, 5015.68553888, 5017.52928888,
       5019.37303888, 5021.22460138, 5023.06835138, 5024.91210138,
       5026.75585138, 6767.12303888, 6768.96678888, 6770.81053888,
       6772.65428888, 6774.49803888, 6776.34178888, 6778.18944513,
       6780.03319513, 6781.87694513, 6783.72460138, 6785.56835138,
       6787.41210138, 6789.25585138, 6791.09960138, 6792.94335138,
       6794.79100763, 6796.63475763, 6798.47850763, 6800.32616388,
       6802.16991388, 6804.01366388, 6805.85741388, 6807.70116388,
       6809.54491388, 6811.39257013, 6813.23632013, 6815.08007013,
       6816.92772638, 6818.77147638, 6820.61522638, 6822.45897638,
       6824.30272638, 6826.14647638, 6827.99413263, 6829.83788263,
       6831.68163263, 6833.52928888, 6835.37303888, 6837.21678888,
       6839.06053888, 6840.90428888, 6842.74803888, 6844.59569513,
       6846.43944513, 6848.28319513, 6850.13085138, 6851.97460138,
       6853.81835138, 6855.66210138, 6857.50585138, 6859.34960138,
       6861.19725763, 6863.04100763, 6864.88475763, 6866.73241388,
       6868.57616388, 6870.41991388, 6872.26366388, 6874.10741388,
       6875.95116388, 6877.79882013, 6879.64257013, 6881.48632013,
       6883.33397638, 6885.17772638, 6887.02147638, 6888.86522638,
       6890.70897638, 6892.55272638, 6894.40038263, 6896.24413263,
       6898.08788263, 6899.93553888, 6901.77928888, 6903.62303888,
       6905.46678888, 6907.31053888, 6909.15428888, 6911.00194513,
       6912.84569513, 6914.68944513, 6916.53710138, 6918.38085138,
       6920.22460138, 6922.06835138, 6923.91210138, 6925.75585138,
       6927.60350763, 6929.44725763, 6931.29100763, 6933.13866388,
       6934.98241388, 6936.82616388, 6938.66991388, 6940.51366388,
       6942.35741388, 6944.20507013, 6946.04882013, 6947.89257013,
       6949.74022638, 6951.58397638, 6953.42772638, 6955.27147638,
       6957.11522638, 6958.96288263, 6960.80663263, 6962.65038263,
       6964.49413263, 6966.34178888, 6968.18553888, 6970.02928888,
       6971.87303888, 6973.71678888, 6975.56444513, 6977.40819513,
       6979.25194513, 6981.09569513, 1951.18553888, 1953.02928888,
       1954.87303888, 1956.72069513, 1958.56444513, 1960.40819513,
       1962.25194513, 1964.09569513, 1965.94335138, 1967.78710138,
       1969.63085138, 1971.47460138, 1973.32225763, 1975.16600763,
       1977.00975763, 1978.85350763, 1980.69725763, 1982.54491388,
       1984.38866388, 1986.23241388, 1988.07616388, 1989.92382013,
       1991.76757013, 1993.61132013, 1995.45507013, 1997.29882013,
       1999.14647638, 2000.99022638, 2002.83397638, 2004.67772638,
       2006.52538263, 2008.36913263, 2010.21288263, 2012.05663263,
       2013.90038263, 2015.74803888, 2017.59178888, 2019.43553888,
       2021.28319513, 2023.12694513, 2024.97069513, 2026.81444513,
       2028.65819513, 2030.50194513, 2032.34960138, 2034.19335138,
       2036.03710138, 2037.88475763, 2039.72850763, 2041.57225763,
       2043.41600763, 2045.25975763, 2047.10350763, 2048.95116388,
       2050.79491388, 2052.63866388, 2054.48632013, 2056.33007013,
       2058.17382013, 2060.01757013, 2061.86132013, 2063.70507013,
       2065.55272638, 2067.39647638, 2069.24022638, 2071.08788263,
       2072.93163263, 2074.77538263, 2076.61913263, 2078.46288263,
       2080.30663263, 2082.15428888, 2083.99803888, 2085.84178888,
       2087.68944513, 2089.53319513, 2091.37694513, 2093.22069513,
       2095.06444513, 2096.90819513, 2098.75585138, 2100.59960138,
       2102.44335138, 2104.29100763, 2106.13475763, 2107.97850763,
       2109.82225763, 2111.66600763, 2113.50975763, 2115.35741388,
       2117.20116388, 2119.04491388, 2120.89257013, 2122.73632013,
       2124.58007013, 2126.42382013, 2128.26757013, 2130.11132013,
       2131.95897638, 2133.80272638, 2135.64647638, 2137.49413263,
       2139.33788263, 2141.18163263, 2143.02538263, 2144.86913263,
       2146.71288263, 2148.56053888, 2150.40428888, 2152.24803888,
       2154.09569513, 2155.93944513, 2157.78319513, 2159.62694513,
       2161.47069513, 2163.31444513, 2165.16210138, 3030.13866388,
       3031.98241388, 3033.82616388, 3035.67382013, 3037.51757013,
       3039.36132013, 3041.20507013, 3043.04882013, 3044.89647638,
       3046.74022638, 3048.58397638, 3050.42772638, 3052.27538263,
       3054.11913263, 3055.96288263, 3057.80663263, 3059.65038263,
       3061.49803888, 3063.34178888, 3065.18553888, 3067.02928888,
       3068.87694513, 3070.72069513, 3072.56444513, 3074.40819513,
       3076.25194513, 3078.09960138, 3079.94335138, 3081.78710138,
       3083.63085138, 3085.47850763, 3087.32225763, 3089.16600763,
       3091.00975763, 3092.85350763, 3094.70116388, 3096.54491388,
       3098.38866388, 3100.23632013, 3102.08007013, 3103.92382013,
       3105.76757013, 3107.61132013, 3109.45507013, 3111.30272638,
       3113.14647638, 3114.99022638, 3116.83788263, 3118.68163263,
       3120.52538263, 3122.36913263, 3124.21288263, 3126.05663263,
       3127.90428888, 3129.74803888, 3131.59178888, 3133.43944513,
       3135.28319513, 3137.12694513, 3138.97069513, 3140.81444513,
       3142.65819513, 3144.50585138, 3146.34960138, 3148.19335138,
       3150.04100763, 3151.88475763, 3153.72850763, 3155.57225763,
       3157.41600763, 3159.25975763, 3161.10741388, 3162.95116388,
       3164.79491388, 3166.64257013, 3168.48632013, 3170.33007013,
       3172.17382013, 3174.01757013, 3175.86132013, 3177.70897638,
       3179.55272638, 3181.39647638, 3183.24413263, 3185.08788263,
       3186.93163263, 3188.77538263, 3190.61913263, 3192.46288263,
       3194.31053888, 3196.15428888, 3197.99803888, 3199.84569513,
       3201.68944513, 3203.53319513, 3205.37694513, 3207.22069513,
       3209.06444513, 3210.91210138, 3212.75585138, 3214.59960138,
       3216.44725763, 3218.29100763, 3220.13475763, 3221.97850763,
       3223.82225763, 3225.66600763, 3227.51366388, 3229.35741388,
       3231.20116388, 3233.04882013, 3234.89257013, 3236.73632013,
       3238.58007013, 3240.42382013, 3242.26757013, 3244.11522638])